In [1]:
import pandas as pd
import numpy as np

In [2]:
path = r"E:\E-commerce Analysis\Data\raw\fato_itens.csv"

In [5]:
df = pd.read_csv (path, sep= ';')

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  112650 non-null  str
 1   order_purchase_timestamp  112650 non-null  str
 2   product_id                112650 non-null  str
 3   product_category_name     111046 non-null  str
 4   seller_id                 112650 non-null  str
 5   price                     112650 non-null  float64
 6   freight_value             112650 non-null  float64
dtypes: float64(2), str(5)
memory usage: 6.0 MB

In [7]:
df.head()

,order_id,order_purchase_timestamp,product_id,product_category_name,seller_id,price,freight_value
0,008fab5602c441d51f30b1464f5d4643,2017-02-22 10:37:41,f23c48d81cd6a0c87f5c3b14aac68371,beleza_saude,ebd2d60905fb58271facef5596b620d3,49.99,15.56
1,016fbc333d66b414be541c6159576c40,2018-05-30 18:09:10,b0cd550945da1de6eb9cb69595d540df,esporte_lazer,6b243f80ed07b10f0e8aa0f21a205f3c,84.90,18.52
2,01835ef41c5ac66dd9ec6084fa1d0533,2017-05-11 21:36:10,bbaef2eadf31fe3ea6702077398be06c,perfumaria,cc419e0650a3c5ba77189a1882b7556a,56.99,15.15
3,01a75ac3dd000b7628a684be97c29234,2018-01-23 10:32:39,b5c114b11d53b6fd85a6a90790f0b479,utilidades_domesticas,0adac9fbd9a2b63cccaac4f8756c1ca8,42.90,15.10
4,03720fdc92032ee4abd471d172006ab0,2018-08-05 21:34:54,dd2ca29c9d0f93d3b1d28d7d7ee3025c,moveis_sala,5b0cc932433fa5184b5b94bfe6bcc256,99.00,44.49

In [11]:
df['order_purchase_timestamp'] = df['order_purchase_timestamp'].astype('datetime64[ns]')
df['product_category_name'] = df['product_category_name'].astype('category')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 112650 entries, 0 to 112649
Data columns (total 7 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  112650 non-null  str
 1   order_purchase_timestamp  112650 non-null  datetime64[ns]
 2   product_id                112650 non-null  str
 3   product_category_name     111046 non-null  category
 4   seller_id                 112650 non-null  str
 5   price                     112650 non-null  float64
 6   freight_value             112650 non-null  float64
dtypes: category(1), datetime64[ns](1), float64(2), str(3)
memory usage: 5.3 MB

In [10]:
df[df.isnull().any(axis=1)]

,order_id,order_purchase_timestamp,product_id,product_category_name,seller_id,price,freight_value
10876,699b7692e65138e6874b4c6f42202974,2018-03-07 16:59:34,c92a8559445ec8f63ecf90c7dd910b7d,NaN,f419677537694f0462a91990df6ca44f,55.90,15.27
10912,9f2c6714edee90964b0b631c22a22448,2018-02-06 01:03:08,27f0ec8644d62c85b25674aaa6d1124c,NaN,42fa4ee7240e9b8eb4576358ec142ba7,165.00,38.70
11249,7cf4d6735272dc5678263c8d9c1144d4,2017-09-27 21:30:35,2b7f2a7cf1025b94bc5dc6c28746beaf,NaN,3771c85bac139d2344864ede5d9341e3,52.80,9.94
11298,bbca89624572b1532cc19840d3ad81c8,2017-02-14 10:55:36,a4d8f727f92014da5dd64116af14634c,NaN,63ffcb71394dd8ea3872ed9ffda17c74,25.00,12.93
11478,c3d98859790f5ef3e0ec03a886506d35,2018-03-20 22:30:20,52a5346c9dae9cd560b103875b94d123,NaN,226b05fe067266c59c15dae208213d06,119.90,18.72
...,...,...,...,...,...,...,...
112300,fc325d6bae67acedec72848583cc6d27,2018-07-18 16:50:53,0533c5ec3a042521493cfb6e12d6befd,NaN,11305281b50fff20ae8bb473f8e11876,49.99,15.42
112301,fc325d6bae67acedec72848583cc6d27,2018-07-18 16:50:53,0533c5ec3a042521493cfb6e12d6befd,NaN,11305281b50fff20ae8bb473f8e11876,49.99,15.42
112439,cfbc27fc3b0b3946a3dea53be0022108,2018-01-22 12:33:43,b36f3c918c91478c4559160022d3f14e,NaN,1ca7077d890b907f89be8c954a02686a,150.00,14.80
112461,eaa0211ae0667cb758713505ee149479,2017-08-21 12:27:20,eaecac42c42a65691bc3662b123e884d,NaN,916748bc99315c2d202898ae58b1617e,15.00,8.27
112492,2d1cfcc5ed3232215b908e86ff33da61,2018-01-21 21:52:15,b36f3c918c91478c4559160022d3f14e,NaN,1ca7077d890b907f89be8c954a02686a,150.00,8.30

In [12]:
df['product_category_name'] = df['product_category_name'].cat.add_categories(['unknown'])
df['product_category_name'] = df['product_category_name'].fillna('unknown')

In [13]:
df[df.isnull().any(axis=1)]

Empty DataFrame
Columns: [order_id, order_purchase_timestamp, product_id, product_category_name, seller_id, price, freight_value]
Index: []

In [14]:
df.isnull().sum()

order_id                    0
order_purchase_timestamp    0
product_id                  0
product_category_name       0
seller_id                   0
price                       0
freight_value               0
dtype: int64

In [15]:
df.head(10)

,order_id,order_purchase_timestamp,product_id,product_category_name,seller_id,price,freight_value
0,008fab5602c441d51f30b1464f5d4643,2017-02-22 10:37:41,f23c48d81cd6a0c87f5c3b14aac68371,beleza_saude,ebd2d60905fb58271facef5596b620d3,49.99,15.56
1,016fbc333d66b414be541c6159576c40,2018-05-30 18:09:10,b0cd550945da1de6eb9cb69595d540df,esporte_lazer,6b243f80ed07b10f0e8aa0f21a205f3c,84.90,18.52
2,01835ef41c5ac66dd9ec6084fa1d0533,2017-05-11 21:36:10,bbaef2eadf31fe3ea6702077398be06c,perfumaria,cc419e0650a3c5ba77189a1882b7556a,56.99,15.15
3,01a75ac3dd000b7628a684be97c29234,2018-01-23 10:32:39,b5c114b11d53b6fd85a6a90790f0b479,utilidades_domesticas,0adac9fbd9a2b63cccaac4f8756c1ca8,42.90,15.10
4,03720fdc92032ee4abd471d172006ab0,2018-08-05 21:34:54,dd2ca29c9d0f93d3b1d28d7d7ee3025c,moveis_sala,5b0cc932433fa5184b5b94bfe6bcc256,99.00,44.49
5,04a59fe46fc5aa341da5378c195ed53c,2017-11-26 09:32:06,2a15783d3cb601f8d9a6a86806b037b3,bebes,855668e0971d4dfd7bef1b6a4133b41b,60.00,15.18
6,04b7738ad5fbb213eeb7a2145bea8242,2018-05-16 10:58:56,9163c7e81fd68452472912c4cde810aa,instrumentos_musicais,b499c00f28f4b7069ff6550af8c1348a,39.99,1.98
7,05d27719c66597da0628a53f6009ed67,2017-11-01 19:01:18,386486367c1f9d4f587a8864ccb6902b,cama_mesa_banho,cca3071e3e9bb7d12640c9fbe2301306,113.57,13.81
8,05d27719c66597da0628a53f6009ed67,2017-11-01 19:01:18,386486367c1f9d4f587a8864ccb6902b,cama_mesa_banho,cca3071e3e9bb7d12640c9fbe2301306,113.57,13.81
9,062d3e3b803bd3e569cf8c165602f8f4,2018-06-25 17:26:38,19c91ef95d509ea33eda93495c4d3481,beleza_saude,06a2c3af7b3aee5d69171b0e14f0ee87,122.99,63.11

In [16]:
pd.options.display.float_format = '{:.2f}'.format

In [17]:
df.head(10)

,order_id,order_purchase_timestamp,product_id,product_category_name,seller_id,price,freight_value
0,008fab5602c441d51f30b1464f5d4643,2017-02-22 10:37:41,f23c48d81cd6a0c87f5c3b14aac68371,beleza_saude,ebd2d60905fb58271facef5596b620d3,49.99,15.56
1,016fbc333d66b414be541c6159576c40,2018-05-30 18:09:10,b0cd550945da1de6eb9cb69595d540df,esporte_lazer,6b243f80ed07b10f0e8aa0f21a205f3c,84.90,18.52
2,01835ef41c5ac66dd9ec6084fa1d0533,2017-05-11 21:36:10,bbaef2eadf31fe3ea6702077398be06c,perfumaria,cc419e0650a3c5ba77189a1882b7556a,56.99,15.15
3,01a75ac3dd000b7628a684be97c29234,2018-01-23 10:32:39,b5c114b11d53b6fd85a6a90790f0b479,utilidades_domesticas,0adac9fbd9a2b63cccaac4f8756c1ca8,42.90,15.10
4,03720fdc92032ee4abd471d172006ab0,2018-08-05 21:34:54,dd2ca29c9d0f93d3b1d28d7d7ee3025c,moveis_sala,5b0cc932433fa5184b5b94bfe6bcc256,99.00,44.49
5,04a59fe46fc5aa341da5378c195ed53c,2017-11-26 09:32:06,2a15783d3cb601f8d9a6a86806b037b3,bebes,855668e0971d4dfd7bef1b6a4133b41b,60.00,15.18
6,04b7738ad5fbb213eeb7a2145bea8242,2018-05-16 10:58:56,9163c7e81fd68452472912c4cde810aa,instrumentos_musicais,b499c00f28f4b7069ff6550af8c1348a,39.99,1.98
7,05d27719c66597da0628a53f6009ed67,2017-11-01 19:01:18,386486367c1f9d4f587a8864ccb6902b,cama_mesa_banho,cca3071e3e9bb7d12640c9fbe2301306,113.57,13.81
8,05d27719c66597da0628a53f6009ed67,2017-11-01 19:01:18,386486367c1f9d4f587a8864ccb6902b,cama_mesa_banho,cca3071e3e9bb7d12640c9fbe2301306,113.57,13.81
9,062d3e3b803bd3e569cf8c165602f8f4,2018-06-25 17:26:38,19c91ef95d509ea33eda93495c4d3481,beleza_saude,06a2c3af7b3aee5d69171b0e14f0ee87,122.99,63.11

In [18]:
df['total_payment'] = df['price'] + df['freight_value']
df.head(10)

,order_id,order_purchase_timestamp,product_id,product_category_name,seller_id,price,freight_value,total_payment
0,008fab5602c441d51f30b1464f5d4643,2017-02-22 10:37:41,f23c48d81cd6a0c87f5c3b14aac68371,beleza_saude,ebd2d60905fb58271facef5596b620d3,49.99,15.56,65.55
1,016fbc333d66b414be541c6159576c40,2018-05-30 18:09:10,b0cd550945da1de6eb9cb69595d540df,esporte_lazer,6b243f80ed07b10f0e8aa0f21a205f3c,84.90,18.52,103.42
2,01835ef41c5ac66dd9ec6084fa1d0533,2017-05-11 21:36:10,bbaef2eadf31fe3ea6702077398be06c,perfumaria,cc419e0650a3c5ba77189a1882b7556a,56.99,15.15,72.14
3,01a75ac3dd000b7628a684be97c29234,2018-01-23 10:32:39,b5c114b11d53b6fd85a6a90790f0b479,utilidades_domesticas,0adac9fbd9a2b63cccaac4f8756c1ca8,42.90,15.10,58.00
4,03720fdc92032ee4abd471d172006ab0,2018-08-05 21:34:54,dd2ca29c9d0f93d3b1d28d7d7ee3025c,moveis_sala,5b0cc932433fa5184b5b94bfe6bcc256,99.00,44.49,143.49
5,04a59fe46fc5aa341da5378c195ed53c,2017-11-26 09:32:06,2a15783d3cb601f8d9a6a86806b037b3,bebes,855668e0971d4dfd7bef1b6a4133b41b,60.00,15.18,75.18
6,04b7738ad5fbb213eeb7a2145bea8242,2018-05-16 10:58:56,9163c7e81fd68452472912c4cde810aa,instrumentos_musicais,b499c00f28f4b7069ff6550af8c1348a,39.99,1.98,41.97
7,05d27719c66597da0628a53f6009ed67,2017-11-01 19:01:18,386486367c1f9d4f587a8864ccb6902b,cama_mesa_banho,cca3071e3e9bb7d12640c9fbe2301306,113.57,13.81,127.38
8,05d27719c66597da0628a53f6009ed67,2017-11-01 19:01:18,386486367c1f9d4f587a8864ccb6902b,cama_mesa_banho,cca3071e3e9bb7d12640c9fbe2301306,113.57,13.81,127.38
9,062d3e3b803bd3e569cf8c165602f8f4,2018-06-25 17:26:38,19c91ef95d509ea33eda93495c4d3481,beleza_saude,06a2c3af7b3aee5d69171b0e14f0ee87,122.99,63.11,186.10

In [20]:
df.to_csv("fato_itens_tratada.csv", index=False)