In [1]:
import pandas as pd
import numpy as np

In [18]:
path = r"E:\E-commerce Analysis\Data\raw\fato_vendas.csv"

In [19]:
df_FatoVendas = pd.read_csv (path, sep= ';')

In [20]:
df_FatoVendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 11 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  113425 non-null  str
 1   order_purchase_timestamp  113425 non-null  str
 2   order_status              113425 non-null  str
 3   customer_id               113425 non-null  str
 4   customer_state            113425 non-null  str
 5   product_id                112650 non-null  str
 6   product_category_name     111046 non-null  str
 7   seller_id                 112650 non-null  str
 8   price                     113425 non-null  float64
 9   freight_value             113425 non-null  float64
 10  total_payment             113425 non-null  float64
dtypes: float64(3), str(8)
memory usage: 9.5 MB

In [21]:
df_FatoVendas.head()

,order_id,order_purchase_timestamp,order_status,customer_id,customer_state,product_id,product_category_name,seller_id,price,freight_value,total_payment
0,016befe103ce7c9e5b1b7ef359777eea,2017-09-03 10:11:52,delivered,15f3f60c0575a9f2a7d5434f7b8a7692,SP,6c321ed0f47858a8650f4104771224b5,relogios_presentes,6560211a19b47992c3666cc44a7e94c0,49.00,11.85,60.849998
1,035c01a45e289b155db4e47cf39b29d3,2018-08-06 22:01:08,delivered,d68f9c633f9ab44265b54f3792fcbe71,SP,656e0eca68dcecf6a31b8ececfabe3e8,informatica_acessorios,5f67c6082caacb26e431a7b17940cece,79.90,13.90,93.800003
2,b7e339d3c4aefa73f6e86875b78250f3,2017-12-17 22:36:30,delivered,454b89aa74cc3a41ac6a964e7f6c9e67,SP,2029248294c186017ecfc48cecd47bbd,ferramentas_jardim,d50d79cb34e38265a8649c383dcffd48,129.99,17.62,147.610001
3,8e0aba4e9cd80e71b2cec14e22df868b,2017-11-15 12:08:23,delivered,5a23a92261328e087c062a7c265b7862,RN,a1766f2d27b4e90a0d78d8e115295399,perfumaria,17e34d8224d27a541263c4c64b11a56b,102.48,34.52,137.000000
4,9564498225916371a8670c3b0253ea81,2017-05-06 08:54:37,delivered,403d065ed4e3882fb44ac77fe8297132,BA,a99b67c7e525bb5ca667e1aa284c28e2,esporte_lazer,adcf50477d6a1f5d91bb9d54c4903cb5,17.55,26.78,177.320007

In [22]:
df_FatoVendas['order_purchase_timestamp'] = df_FatoVendas['order_purchase_timestamp'].astype('datetime64[ns]')
df_FatoVendas['order_status'] = df_FatoVendas['order_status'].astype('category')
df_FatoVendas['customer_state'] = df_FatoVendas['customer_state'].astype('category')
df_FatoVendas['product_category_name'] = df_FatoVendas['product_category_name'].astype('category')

df_FatoVendas['price'] = df_FatoVendas['price'].astype('float32')
df_FatoVendas['freight_value'] = df_FatoVendas['freight_value'].astype('float32')
df_FatoVendas['total_payment'] = df_FatoVendas['total_payment'].astype('float32')

In [23]:
df_FatoVendas[df_FatoVendas.isnull().any(axis=1)]

,order_id,order_purchase_timestamp,order_status,customer_id,customer_state,product_id,product_category_name,seller_id,price,freight_value,total_payment
388,2de6a60c0b5386778d202e28d688553c,2017-05-12 10:24:16,delivered,2177339c6c7841dd2233b686a3566bcc,SP,a4d8f727f92014da5dd64116af14634c,NaN,63ffcb71394dd8ea3872ed9ffda17c74,25.000000,16.600000,41.599998
429,dd6644d86c2b8177a9ae5f51bbf7b82a,2018-01-11 23:04:21,delivered,cd7333a35d439e7d2c03da35747f0d78,SP,ad88641611c35ebd59ecda07a9f17099,NaN,c826c40d7b19f62a09e2d7c5e7295ee2,157.770004,9.300000,167.070007
453,96de2b7f7f3c401fbee3eef068376da6,2018-01-01 20:11:53,delivered,eec30b788184a6d93954fd5e82c48add,SP,9689d8153681f3d8bc3e88622c013b08,NaN,e5a3438891c0bfdb9394643f95273d8e,20.299999,11.850000,32.150002
510,b667484df2bb8bef1e61788f1c7556f5,2018-01-05 14:50:02,delivered,a4db066a833b0fcd698e7eeba2d73fe9,SP,ad88641611c35ebd59ecda07a9f17099,NaN,c826c40d7b19f62a09e2d7c5e7295ee2,157.770004,12.600000,170.369995
528,047723564a4f371af7f16f08f08ae0e0,2017-12-06 19:03:12,delivered,7432c3797af23ca4b5544ec87f893259,RJ,f58e45b16a42a325c144eb2c46a2bc57,NaN,46dc3b2cc0980fb8ec44634e21d2718e,279.989990,19.400000,299.390015
...,...,...,...,...,...,...,...,...,...,...,...
113306,974f9f87a3bad01b2ac72fe987505e9b,2017-06-09 20:25:03,unavailable,b8bd03cdd075b29c82a9c55e5cd8e224,MG,NaN,NaN,NaN,0.000000,0.000000,91.180000
113307,7159096c5aa9be77f7f0c26c01ee9793,2018-03-15 10:06:35,canceled,d8f3aacf5cf5ddf9ceef4ad39e874c98,MS,NaN,NaN,NaN,0.000000,0.000000,280.649994
113320,1ad1ca4550bd6dbd299d8538a86e5400,2017-04-01 09:50:09,delivered,30f9adf897b5a65c80f9a9fb5bd03234,SP,e891d4a9622cae3b9fc2ec558bda155b,NaN,e603cf3fec55f8697c9059638d6c8eb5,27.000000,16.049999,43.049999
113355,312384a598132f165ae6f58bc210f8fb,2017-11-27 15:39:09,delivered,69deddc9a3d17bcc5d20eee6ab2d43b1,RJ,00d62b338366db4c4aec8547ea8f928e,NaN,c0f783394e37cd9c9d7f5f81141450fa,29.900000,15.100000,45.000000
113410,6eb2780615aa0cfbaaef6c8d0aec411a,2018-01-22 07:15:14,delivered,09f5cf3f546f034dba3dffbe08fe48ec,SP,b36f3c918c91478c4559160022d3f14e,NaN,1ca7077d890b907f89be8c954a02686a,150.000000,8.300000,158.300003

In [24]:
df_FatoVendas[
    (df_FatoVendas['order_status'].notnull()) &
    (df_FatoVendas['product_category_name'].isnull())
]

,order_id,order_purchase_timestamp,order_status,customer_id,customer_state,product_id,product_category_name,seller_id,price,freight_value,total_payment
388,2de6a60c0b5386778d202e28d688553c,2017-05-12 10:24:16,delivered,2177339c6c7841dd2233b686a3566bcc,SP,a4d8f727f92014da5dd64116af14634c,NaN,63ffcb71394dd8ea3872ed9ffda17c74,25.000000,16.600000,41.599998
429,dd6644d86c2b8177a9ae5f51bbf7b82a,2018-01-11 23:04:21,delivered,cd7333a35d439e7d2c03da35747f0d78,SP,ad88641611c35ebd59ecda07a9f17099,NaN,c826c40d7b19f62a09e2d7c5e7295ee2,157.770004,9.300000,167.070007
453,96de2b7f7f3c401fbee3eef068376da6,2018-01-01 20:11:53,delivered,eec30b788184a6d93954fd5e82c48add,SP,9689d8153681f3d8bc3e88622c013b08,NaN,e5a3438891c0bfdb9394643f95273d8e,20.299999,11.850000,32.150002
510,b667484df2bb8bef1e61788f1c7556f5,2018-01-05 14:50:02,delivered,a4db066a833b0fcd698e7eeba2d73fe9,SP,ad88641611c35ebd59ecda07a9f17099,NaN,c826c40d7b19f62a09e2d7c5e7295ee2,157.770004,12.600000,170.369995
528,047723564a4f371af7f16f08f08ae0e0,2017-12-06 19:03:12,delivered,7432c3797af23ca4b5544ec87f893259,RJ,f58e45b16a42a325c144eb2c46a2bc57,NaN,46dc3b2cc0980fb8ec44634e21d2718e,279.989990,19.400000,299.390015
...,...,...,...,...,...,...,...,...,...,...,...
113306,974f9f87a3bad01b2ac72fe987505e9b,2017-06-09 20:25:03,unavailable,b8bd03cdd075b29c82a9c55e5cd8e224,MG,NaN,NaN,NaN,0.000000,0.000000,91.180000
113307,7159096c5aa9be77f7f0c26c01ee9793,2018-03-15 10:06:35,canceled,d8f3aacf5cf5ddf9ceef4ad39e874c98,MS,NaN,NaN,NaN,0.000000,0.000000,280.649994
113320,1ad1ca4550bd6dbd299d8538a86e5400,2017-04-01 09:50:09,delivered,30f9adf897b5a65c80f9a9fb5bd03234,SP,e891d4a9622cae3b9fc2ec558bda155b,NaN,e603cf3fec55f8697c9059638d6c8eb5,27.000000,16.049999,43.049999
113355,312384a598132f165ae6f58bc210f8fb,2017-11-27 15:39:09,delivered,69deddc9a3d17bcc5d20eee6ab2d43b1,RJ,00d62b338366db4c4aec8547ea8f928e,NaN,c0f783394e37cd9c9d7f5f81141450fa,29.900000,15.100000,45.000000
113410,6eb2780615aa0cfbaaef6c8d0aec411a,2018-01-22 07:15:14,delivered,09f5cf3f546f034dba3dffbe08fe48ec,SP,b36f3c918c91478c4559160022d3f14e,NaN,1ca7077d890b907f89be8c954a02686a,150.000000,8.300000,158.300003

In [25]:
df_FatoVendas['product_category_name'] = df_FatoVendas['product_category_name'].cat.add_categories(['unknown'])

df_FatoVendas.loc[
    (df_FatoVendas['order_status'] == 'delivered') &
    (df_FatoVendas['product_category_name'].isnull()),
    'product_category_name'
] = 'unknown'

In [31]:
df_FatoVendas.isnull().sum()

order_id                      0
order_purchase_timestamp      0
order_status                  0
customer_id                   0
customer_state                0
product_id                  775
product_category_name         0
seller_id                   775
price                         0
freight_value                 0
total_payment                 0
dtype: int64

In [27]:
df_FatoVendas['product_category_name'] = df_FatoVendas['product_category_name'].fillna('unknown')

In [ ]:
df_FatoVendas.head(10)

,order_id,order_purchase_timestamp,order_status,customer_id,customer_state,product_id,product_category_name,seller_id,price,freight_value,total_payment
0,016befe103ce7c9e5b1b7ef359777eea,2017-09-03 10:11:52,delivered,15f3f60c0575a9f2a7d5434f7b8a7692,SP,6c321ed0f47858a8650f4104771224b5,relogios_presentes,6560211a19b47992c3666cc44a7e94c0,49.00,11.85,60.85
1,035c01a45e289b155db4e47cf39b29d3,2018-08-06 22:01:08,delivered,d68f9c633f9ab44265b54f3792fcbe71,SP,656e0eca68dcecf6a31b8ececfabe3e8,informatica_acessorios,5f67c6082caacb26e431a7b17940cece,79.90,13.90,93.80
2,b7e339d3c4aefa73f6e86875b78250f3,2017-12-17 22:36:30,delivered,454b89aa74cc3a41ac6a964e7f6c9e67,SP,2029248294c186017ecfc48cecd47bbd,ferramentas_jardim,d50d79cb34e38265a8649c383dcffd48,129.99,17.62,147.61
3,8e0aba4e9cd80e71b2cec14e22df868b,2017-11-15 12:08:23,delivered,5a23a92261328e087c062a7c265b7862,RN,a1766f2d27b4e90a0d78d8e115295399,perfumaria,17e34d8224d27a541263c4c64b11a56b,102.48,34.52,137.00
4,9564498225916371a8670c3b0253ea81,2017-05-06 08:54:37,delivered,403d065ed4e3882fb44ac77fe8297132,BA,a99b67c7e525bb5ca667e1aa284c28e2,esporte_lazer,adcf50477d6a1f5d91bb9d54c4903cb5,17.55,26.78,177.32
5,9564498225916371a8670c3b0253ea81,2017-05-06 08:54:37,delivered,403d065ed4e3882fb44ac77fe8297132,BA,a99b67c7e525bb5ca667e1aa284c28e2,esporte_lazer,adcf50477d6a1f5d91bb9d54c4903cb5,17.55,26.78,177.32
6,9564498225916371a8670c3b0253ea81,2017-05-06 08:54:37,delivered,403d065ed4e3882fb44ac77fe8297132,BA,a99b67c7e525bb5ca667e1aa284c28e2,esporte_lazer,adcf50477d6a1f5d91bb9d54c4903cb5,17.55,26.78,177.32
7,9564498225916371a8670c3b0253ea81,2017-05-06 08:54:37,delivered,403d065ed4e3882fb44ac77fe8297132,BA,a99b67c7e525bb5ca667e1aa284c28e2,esporte_lazer,adcf50477d6a1f5d91bb9d54c4903cb5,17.55,26.78,177.32
8,c3fa73017c4a172907d79669eda248d0,2017-10-08 22:59:49,delivered,58830055981413a6c6eb3b4b45561b5f,RJ,d7e2d29c1596c2eb1e6e0c85f27cc81f,moveis_decoracao,77530e9772f57a62c906e1c21538ab82,119.00,20.07,139.07
9,cf014dc8804713618176fc95af41b221,2018-06-28 00:41:07,delivered,67ec955996d7971b82e80aea6029aead,CE,c477957dd9b5f51032f3631c50630585,cama_mesa_banho,d0d70d21e2234dd7cd3cf63fe414148a,39.90,18.43,131.66

In [30]:
df_FatoVendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 113425 entries, 0 to 113424
Data columns (total 11 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   order_id                  113425 non-null  str
 1   order_purchase_timestamp  113425 non-null  datetime64[ns]
 2   order_status              113425 non-null  category
 3   customer_id               113425 non-null  str
 4   customer_state            113425 non-null  category
 5   product_id                112650 non-null  str
 6   product_category_name     113425 non-null  category
 7   seller_id                 112650 non-null  str
 8   price                     113425 non-null  float32
 9   freight_value             113425 non-null  float32
 10  total_payment             113425 non-null  float32
dtypes: category(3), datetime64[ns](1), float32(3), str(4)
memory usage: 6.0 MB

In [29]:
pd.options.display.float_format = '{:.2f}'.format